site_name: pySNOW Documentation

theme:
  name: material
  
  logo: assets/logo_2.png
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - content.footnote.tooltips
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange


nav:
  - Home: home.md
  - Installation: install.md
  - Physics: physics.md

  - Modules:
    - descriptors:
        - distributions:     descriptors/distributions.md
        - coordination:      descriptors/coordination.md
        - cna:               descriptors/cna.md
        - saxs:              descriptors/saxs.md
        - shape_descriptors: descriptors/shape_descriptors.md
        - time_dependent:    descriptors/time_dependent.md
        - utils:             descriptors/utils.md
    - catalysis:
        - add_molecule: catalysis/add_molecule.md
    - misc:
        - transform: misc/rototranslation.md
    - io:
        - xyz: io/xyz.md
        - lammps: io/lammps.md

    - Tutorials: tutorials.md

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.blocks.caption

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          show_source: true #collapsible show_source button
          show_root_heading: true #show where we are
          members_order: source    # keeps the order from the source file

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
copyright: Copyright &copy; 2025 nanoMLMS
site_dir: site
